name: theworks
description: "the"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.0.2
  firebase_performance: ^0.11.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.3
  choice: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/testgrad.png
    - assets/images/TESTLOGO.png
    - assets/tags.json

  fonts:
    - family: KumbhSans
      fonts:
        - asset: assets/fonts/KumbhSans.ttf
